# Generated by Django 4.0.1 on 2022-01-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=' SELL OR BUY 0.1 BITCOIN'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=' SELL OR BUY COIN', max_length=255),
        ),
    ]
