# Generated by Django 4.0 on 2022-01-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
