# Generated by Django 4.0 on 2022-02-05 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_binance_bitcoin_ethereum_tether'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Binance',
        ),
        migrations.DeleteModel(
            name='Bitcoin',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='Ethereum',
        ),
        migrations.DeleteModel(
            name='Tether',
        ),
    ]
