# Generated by Django 4.0 on 2022-02-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_likes_comment_commentlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
