# Generated by Django 4.0 on 2022-02-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentlikes',
        ),
    ]
